### ISSUE TITLE
whenever i create a server there are no screens

### ISSUE THREAD

**Issue by shirdono** [lordofwizard/mcserver#12]
whenever i create a server there are no screens maybe this is because of the 1.17 update?

**Comment by Enjoyinbreaks** [comment]
Same Here, I also have the same issue. No fixes yet.

**Comment by lordofwizard** [comment]
Yeah. i am doing some testing. Been busy with some stuff. 1.17 has a other way of starting screen sessions. also i am planning to completely re write the session part in tmux. Lot of improvments are still remaining. but if you really wanna use the server. try checking out the old build. i know it's barebones and you need to configure most of the stuff manually. but it's worth giving a try.[ngrok btw]
https://github.com/lordofwizard/minecraftserver

**Comment by shirdono** [comment]
i cant update it to java16 because i want to run a 1.17 server...

**Comment by lordofwizard** [comment]
@shirdono I know. it's because new java 1.17 servers uses java 16+ i am currently making a new patch for it. Due to java 16 being updated in Debian Bullseye and not in Debian buster. it can take months for it to come in stable branch. But i am trying my best to get the servers up and running. Sorry for this inconvinience. there's nothing i can do atm. I have figured out how to get java 16 up and running on our google cloud servers i need some time to automate it for 1.17

**Comment by lordofwizard** [comment]
its fixed
