### ISSUE TITLE
How to go to The panel I make the server and i shutdown my pc and i start github and go to my server the panel is not opening plz help 

### ISSUE THREAD

**Issue by ghost** [lordofwizard/mcserver#67]

**Comment by lordofwizard** [comment]
@TerracottaPlayz Dude, explain in detail.

did u went into the mcserver again?

` cd ~/mcserver`

**Comment by TerracottaPlayz** [comment]
@lordofwizard I make a minecraft server and when i lose the tab in i come in 5 hour i open github and open the code and open the minecraft server panel and i try to login but it was not loging and my code was deleted

**Comment by TerracottaPlayz** [comment]
@lordofwizard are you owner of this ?

**Comment by TerracottaPlayz** [comment]
@lordofwizard one problem again my code is not opening do you have discord i will tell you in vc

**Comment by lordofwizard** [comment]
@TerracottaPlayz https://discord.gg/SCpbQt2Z

**Comment by lordofwizard** [comment]
@TerracottaPlayz , Yes I am the owner. That happend because you were most likely using google cloud in **EPHEMERAL** mode. What this does it, whenever you restart the server the storage in your cloud drive gets deleted. You shouldn't setup your server in Ephemeral mode as you would want to use the world multiple times. There's an option in google cloud shell to disable this. 

![image](https://github.com/lordofwizard/mcserver/assets/38832648/d36921d2-ba83-4c02-9d7f-db93e70e6c7c)


Hope this helps, to address your issue, hop on discord anytime and Ping me.

**Comment by TerracottaPlayz** [comment]
@lordofwizard  So You are saying me that i want to enable Ephemeral mode but one problem is more 
![Uploading Screenshot_15-3-2024_72326_github.com.jpeg…]()

**Comment by TerracottaPlayz** [comment]
@lordofwizard  see this a new prm 
![Screenshot_15-3-2024_131153_console cloud google com](https://github.com/lordofwizard/mcserver/assets/161585899/ebc5cca5-0bc9-47d0-bb5d-5c505dedfde3)

**Comment by Silent-Crafter** [comment]
"mcserver" already exists. It clearly says that.

So just enter this command first. This changes your folder to mcserver folder:
```sh
cd mcserver
```

and after that run this command to start the server:
```sh
./startserver
```
