### ISSUE TITLE
No Eula

### ISSUE THREAD

**Issue by OxxyMystic6966** [lordofwizard/mcserver#70]
Hello, I used the google cloud server host and everything was going good until when I turn on the server, it doesn't seem to turn on but 
it just showing the console is reading the eula text but I thought it would take some time but turns out it didn't even work it's just showing -->
  Your server just doing a second restart to fix the EULA file.
> Starting the server up. Please wait...
> Installing Dependencise...
and on and on and on 
so I went to look the server file and turns out I found NO EULA FILE WHICH INCLUDES eula=true
so please fix it.

**Comment by Kirkezz** [comment]
This happens due to a new discord policy: https://www.bleepingcomputer.com/news/security/discord-will-switch-to-temporary-file-links-to-block-malware-delivery/
script tried to download eula.txt from http://web.archive.org/web/20231212002035/https://cdn.discordapp.com/attachments/715123369200189460/846712565530624050/eula.txt (http://web.archive.org/web/20231212002035/https://cdn.discordapp.com/attachments/715123369200189460/846712565530624050/eula.txt) and fails.
